In [24]:
import pandas as pd
df = pd.read_csv("data_cleaning_sample.csv")
print(df)

      Name   Age         City Gender              Email Join Date
0    Alice  25.0     New York      F  alice@example.com  01/05/21
1  Charlie   NaN        Delhi      M    charlie@example  20/07/21
2      Bob  30.0  Los Angeles      M    bob@example.com  15/06/20
3  Charlie   NaN        Delhi      M    charlie@example  20/07/21
4    David  22.0       Mumbai      M  david@example.com  12/11/19
5      NaN  28.0        Delhi      F     eve@domain.com       NaN
6    Alice  25.0     New York      F  alice@example.com  01/05/21
7    Alice  25.0     New York      F  alice@example.com  01/05/21
8  Charlie   NaN        Delhi      M    charlie@example  20/07/21

# Handling Missing Values

In [25]:
df.isnull() # True for NaNs

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [26]:
df.isnull().sum() # Count missing per column

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

# Drop Missing Data

In [27]:
df.dropna()  # Drop rows with *any* missing values

    Name   Age         City Gender              Email Join Date
0  Alice  25.0     New York      F  alice@example.com  01/05/21
2    Bob  30.0  Los Angeles      M    bob@example.com  15/06/20
4  David  22.0       Mumbai      M  david@example.com  12/11/19
6  Alice  25.0     New York      F  alice@example.com  01/05/21
7  Alice  25.0     New York      F  alice@example.com  01/05/21

In [28]:
df.dropna(axis=1) # Drop columns with missing values

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

# Fill Missing Data

In pandas, fillna is used to fill unknown values. ffill and bfill are methods used to fill missing values (like NaN, None, or pd.NA) by propagating values forward or backward.

In [29]:
df.fillna(0) # Replace NaN with 0

      Name   Age         City Gender              Email Join Date
0    Alice  25.0     New York      F  alice@example.com  01/05/21
1  Charlie   0.0        Delhi      M    charlie@example  20/07/21
2      Bob  30.0  Los Angeles      M    bob@example.com  15/06/20
3  Charlie   0.0        Delhi      M    charlie@example  20/07/21
4    David  22.0       Mumbai      M  david@example.com  12/11/19
5        0  28.0        Delhi      F     eve@domain.com         0
6    Alice  25.0     New York      F  alice@example.com  01/05/21
7    Alice  25.0     New York      F  alice@example.com  01/05/21
8  Charlie   0.0        Delhi      M    charlie@example  20/07/21

In [30]:
df["Age"].fillna(df["Age"].mean()) # Replace with mean

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [31]:
df.bfill() # Backword fill

      Name   Age         City Gender              Email Join Date
0    Alice  25.0     New York      F  alice@example.com  01/05/21
1  Charlie  30.0        Delhi      M    charlie@example  20/07/21
2      Bob  30.0  Los Angeles      M    bob@example.com  15/06/20
3  Charlie  22.0        Delhi      M    charlie@example  20/07/21
4    David  22.0       Mumbai      M  david@example.com  12/11/19
5    Alice  28.0        Delhi      F     eve@domain.com  01/05/21
6    Alice  25.0     New York      F  alice@example.com  01/05/21
7    Alice  25.0     New York      F  alice@example.com  01/05/21
8  Charlie   NaN        Delhi      M    charlie@example  20/07/21

In [84]:
df.ffill() # Forward fill

      Name   Age         City Gender              Email Join Date
0    Alice  25.0     New York      F  alice@example.com  01/05/21
1  Charlie  25.0        Delhi      M    charlie@example  20/07/21
2      Bob  30.0  Los Angeles      M    bob@example.com  15/06/20
3  Charlie  30.0        Delhi      M    charlie@example  20/07/21
4    David  22.0       Mumbai      M  david@example.com  12/11/19
5    David  28.0        Delhi      F     eve@domain.com  12/11/19
6    Alice  25.0     New York      F  alice@example.com  01/05/21
7    Alice  25.0     New York      F  alice@example.com  01/05/21
8  Charlie  25.0        Delhi      M    charlie@example  20/07/21

In [32]:
df

      Name   Age         City Gender              Email Join Date
0    Alice  25.0     New York      F  alice@example.com  01/05/21
1  Charlie   NaN        Delhi      M    charlie@example  20/07/21
2      Bob  30.0  Los Angeles      M    bob@example.com  15/06/20
3  Charlie   NaN        Delhi      M    charlie@example  20/07/21
4    David  22.0       Mumbai      M  david@example.com  12/11/19
5      NaN  28.0        Delhi      F     eve@domain.com       NaN
6    Alice  25.0     New York      F  alice@example.com  01/05/21
7    Alice  25.0     New York      F  alice@example.com  01/05/21
8  Charlie   NaN        Delhi      M    charlie@example  20/07/21

# Detecting & Removing Duplicates

df.duplicated() returns a boolean Series where: True means that row is a duplicate of a previous row. False means it's the first occurrence (not a duplicate yet).

In [33]:
df.duplicated()  # True for duplicates

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [34]:
df.drop_duplicates()  # Remove duplicate rows

      Name   Age         City Gender              Email Join Date
0    Alice  25.0     New York      F  alice@example.com  01/05/21
1  Charlie   NaN        Delhi      M    charlie@example  20/07/21
2      Bob  30.0  Los Angeles      M    bob@example.com  15/06/20
4    David  22.0       Mumbai      M  david@example.com  12/11/19
5      NaN  28.0        Delhi      F     eve@domain.com       NaN

In [36]:
df.duplicated(subset=["Name","Age"]) # Check based on specific columns

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

# String Operations with .str

Works like vectorized string methods and returns a pandas Series:

In [37]:
df["Name"].str.lower() # Converts all names to lowercase.

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: str

In [42]:
df["City"].str.contains("delhi", case=False) # Checks if 'delhi' is in the city name, case-insensitive.

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [43]:
df["Email"].str.split("@") 
# Outputs a pandas Series where each element is a list of strings 
#(the split parts). This is where a Python list comes into play, but the outer object is still a pandas Series.

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [46]:
type(df["Email"].str.split("@")[1])

list

We can always chain methods like .str.strip().str.upper() for clean-up.

In [47]:
df

      Name   Age         City Gender              Email Join Date
0    Alice  25.0     New York      F  alice@example.com  01/05/21
1  Charlie   NaN        Delhi      M    charlie@example  20/07/21
2      Bob  30.0  Los Angeles      M    bob@example.com  15/06/20
3  Charlie   NaN        Delhi      M    charlie@example  20/07/21
4    David  22.0       Mumbai      M  david@example.com  12/11/19
5      NaN  28.0        Delhi      F     eve@domain.com       NaN
6    Alice  25.0     New York      F  alice@example.com  01/05/21
7    Alice  25.0     New York      F  alice@example.com  01/05/21
8  Charlie   NaN        Delhi      M    charlie@example  20/07/21

# Type Conversions with .astype()
Convert column data types:

In [48]:
df2 = df.dropna().copy()

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      str
 1   Age        6 non-null      float64
 2   City       9 non-null      str
 3   Gender     9 non-null      str
 4   Email      9 non-null      str
 5   Join Date  8 non-null      str
dtypes: float64(1), str(5)
memory usage: 564.0 bytes

In [63]:
df2['Age']= df2['Age'].astype(int)

In [64]:
df2.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      str
 1   Age        5 non-null      int64
 2   City       5 non-null      str
 3   Gender     5 non-null      str
 4   Email      5 non-null      str
 5   Join Date  5 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 280.0 bytes

In [65]:
df2['Join Date'] = pd.to_datetime(df2["Join Date"])

In [66]:
df2.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      str
 1   Age        5 non-null      int64
 2   City       5 non-null      str
 3   Gender     5 non-null      str
 4   Email      5 non-null      str
 5   Join Date  5 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 280.0 bytes

In [68]:
df2.dtypes

Name                    str
Age                   int64
City                    str
Gender                  str
Email                   str
Join Date    datetime64[us]
dtype: object

Why is pd.to_datetime() special?
Unlike astype(), which works on simple data types (like integers, strings, etc.), pd.to_datetime() is designed to:

Handle different date formats (e.g., "YYYY-MM-DD", "MM/DD/YYYY", etc.).

Handle mixed types (e.g., some date strings, some NaT, or missing values).

Convert integer timestamps (e.g., UNIX time) into datetime objects.

Recognize timezones if provided.

Check data types:

df.dtypes

In [69]:
df2

    Name  Age         City Gender              Email  Join Date
0  Alice   25     New York      F  alice@example.com 2021-01-05
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15
4  David   22       Mumbai      M  david@example.com 2019-12-11
6  Alice   25     New York      F  alice@example.com 2021-01-05
7  Alice   25     New York      F  alice@example.com 2021-01-05

# Applying Functions

.apply() → Apply any function to rows or columns

In [75]:
def isminor(x):
    return  "Adult" if x >=25 else "Minor"
    
df2['Age Group'] = df2['Age'].apply(isminor)

In [76]:
# df2['Age Group'] = df2['Age'].apply(lambda x : "Adult" if x >25 else "Minor")

In [77]:
df2

    Name  Age         City Gender              Email  Join Date Age Group
0  Alice   25     New York      F  alice@example.com 2021-01-05     Adult
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15     Adult
4  David   22       Mumbai      M  david@example.com 2019-12-11     Minor
6  Alice   25     New York      F  alice@example.com 2021-01-05     Adult
7  Alice   25     New York      F  alice@example.com 2021-01-05     Adult

.map() → Element-wise mapping for Series

In [79]:
gender_map = {"M":"Male" , "F":"Female" , "O":"Other"}
df2['Gender'] = df2["Gender"].map(gender_map)

In [81]:
print(df2)

    Name  Age         City  Gender              Email  Join Date Age Group
0  Alice   25     New York  Female  alice@example.com 2021-01-05     Adult
2    Bob   30  Los Angeles    Male    bob@example.com 2020-06-15     Adult
4  David   22       Mumbai    Male  david@example.com 2019-12-11     Minor
6  Alice   25     New York  Female  alice@example.com 2021-01-05     Adult
7  Alice   25     New York  Female  alice@example.com 2021-01-05     Adult

.replace() → Replace specific values

In [82]:
df2['City']= df2['City'].replace({"New York":"NYC","Mumbai":"New Mumbai"})

In [83]:
df2

    Name  Age         City  Gender              Email  Join Date Age Group
0  Alice   25          NYC  Female  alice@example.com 2021-01-05     Adult
2    Bob   30  Los Angeles    Male    bob@example.com 2020-06-15     Adult
4  David   22   New Mumbai    Male  david@example.com 2019-12-11     Minor
6  Alice   25          NYC  Female  alice@example.com 2021-01-05     Adult
7  Alice   25          NYC  Female  alice@example.com 2021-01-05     Adult