In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("Newdata.csv")

In [17]:
print(df)

                 Actor                      Film  Year            Genre  \
0       Shah Rukh Khan                   Pathaan  2023           Action
1          Salman Khan           Tiger Zinda Hai  2017           Action
2           Aamir Khan                    Dangal  2016        Biography
3        Ranbir Kapoor                Brahmastra  2022          Fantasy
4        Ranveer Singh                 Padmaavat  2018       Historical
5   Ayushmann Khurrana                 Andhadhun  2018         Thriller
6        Rajkummar Rao                     Stree  2018    Horror Comedy
7       Hrithik Roshan                       War  2019           Action
8         Akshay Kumar                Good Newwz  2019           Comedy
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022    Horror Comedy
10        Varun Dhawan     Badrinath Ki Dulhania  2017  Romantic Comedy
11       Vicky Kaushal  Uri: The Surgical Strike  2019           Action

    BoxOffice(INR Crore)  IMDb
0                   1050   7.2
1                    565   6.0
2                   2024   8.4
3                    431   5.6
4                    585   7.0
5                    111   8.3
6                    180   7.5
7                    475   6.5
8                    318   7.0
9                    266   5.9
10                   201   6.1
11                   342   8.2

# Selecting Column & Columns

In [18]:
df['Actor'] # Single column (as Series)

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: str

In [19]:
type(df['Actor'])

pandas.Series

In [23]:
df[['Actor','Film','Year']] # Multiple columns (as DataFrame)

                 Actor                      Film  Year
0       Shah Rukh Khan                   Pathaan  2023
1          Salman Khan           Tiger Zinda Hai  2017
2           Aamir Khan                    Dangal  2016
3        Ranbir Kapoor                Brahmastra  2022
4        Ranveer Singh                 Padmaavat  2018
5   Ayushmann Khurrana                 Andhadhun  2018
6        Rajkummar Rao                     Stree  2018
7       Hrithik Roshan                       War  2019
8         Akshay Kumar                Good Newwz  2019
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022
10        Varun Dhawan     Badrinath Ki Dulhania  2017
11       Vicky Kaushal  Uri: The Surgical Strike  2019

In [26]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

# Selecting Rows by Index

Use .loc[] (label-based) and .iloc[] (position-based):

In [24]:
df.loc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [25]:
df.iloc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

# Select Specific Rows and Columns

In [31]:
df.loc[8,'IMDb'] # Value at row 8, column 'IMDb'

np.float64(7.0)

In [33]:
df.iloc[7,5] # Value at row 7, column at index 5

np.float64(6.5)

In [34]:
df.loc[0:2,["Actor","IMDb"]] # Rows 0 to 2, selected columns

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0
2      Aamir Khan   8.4

In [36]:
df.iloc[0:2,0:2] # Rows and cols by index position

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

# Fast Access: .at and .iat

These are optimized for single element access:

In [38]:
df.at[0,"Actor"] # Fast label-based access

'Shah Rukh Khan'

In [40]:
df.iat[0,0] # Fast position-based access

'Shah Rukh Khan'

# Filtering with Conditions

Simple Condition:

In [43]:
df[df["IMDb"]>6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

Multiple Conditions (AND / OR)

In [55]:
df[(df["IMDb"] > 6) | (df["Year"] > 2019)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

# Querying with .query()

The .query() method in pandas lets you filter DataFrame rows using a string expression — it's a more readable and often more concise alternative to using boolean indexing.
This is a cleaner, SQL-like way to filter:

In [60]:
df.query("Year >= 2019 and IMDb > 8")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [62]:
df.query("Actor == 'Kartik Aaryan' ")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

Here are the main rules and tips for using .query() in pandas:

1. Column names become variables
You can reference column names directly in the query string:

df.query("age > 25 and city == 'Delhi'")

2. String values must be in quotes
Use single or double quotes around strings in the expression:

df.query("name == 'Harry'")

If you have quotes inside quotes, mix them:

df.query('city == "Mumbai"')

3. Use backticks for column names with spaces or special characters
If a column name has spaces, use backticks (`):

df.query("`first name` == 'Alice'")

4. You can use @ to reference Python variables
To pass external variables into .query():

age_limit = 30
df.query("age > @age_limit")

5. Logical operators
Use these:

and, or, not — instead of &, |, ~

==, !=, <, >, <=, >=
Bad:

df.query("age > 30 & city == 'Delhi'")  # ❌

Good:

df.query("age > 30 and city == 'Delhi'")  # ✅

6. Chained comparisons
Just like Python:

df.query("25 < age <= 40")

7. Avoid using reserved keywords as column names
If you have a column named class, lambda, etc., you’ll need to use backticks:

df.query("`class` == 'Physics'")

8. Case-sensitive
Column names and string values are case-sensitive:

df.query("City == 'delhi'")  # ❌ if actual value is 'Delhi'

9. .query() returns a copy, not a view
The result is a new DataFrame. Changes won't affect the original unless reassigned:

filtered = df.query("age < 50")