melt() — Wide to Long
The melt() method in Pandas is used to unpivot a DataFrame from wide format to long format. In other words, it takes columns that represent different variables and combines them into key-value pairs (i.e., long-form data).

When to Use melt():
When you have a DataFrame where each row is an observation, and each column represents a different variable or measurement, and you want to reshape the data into a longer format for easier analysis or visualization.

Syntax:
df.melt(id_vars=None, value_vars=None, var_name=None, value_name="value", col_level=None)

Parameters:
id_vars: The columns that you want to keep fixed (these columns will remain as identifiers).
value_vars: The columns you want to unpivot (the ones you want to "melt" into a single column).
var_name: The name to use for the new column that will contain the names of the melted columns (default is 'variable').
value_name: The name to use for the new column that will contain the values from the melted columns (default is 'value').
col_level: Used for multi-level column DataFrames.

In [1]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [2]:
df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"], var_name="Subject", value_name="Score")

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

Explanation:
id_vars=["Name"]: We keep the "Name" column as it is because it's the identifier.
value_vars=["Math", "Science", "English"]: These are the columns we want to melt.
var_name="Subject": The new column containing the names of the subjects.
value_name="Score": The new column containing the scores.

# pivot() — Long to Wide
The pivot() function in Pandas is used to reshape data, specifically to turn long-format data into wide-format data. This is the reverse operation of melt().

How it works:
pivot() takes a long-format DataFrame and turns it into a wide-format DataFrame by specifying which columns will become the new columns, the rows, and the values.
Syntax:
df.pivot(index=None, columns=None, values=None)

Parameters:
index: The column whose unique values will become the rows of the new DataFrame.
columns: The column whose unique values will become the columns of the new DataFrame.
values: The column whose values will fill the new DataFrame. These will become the actual data (values in the table).

In [12]:
df_long = df.melt(
    id_vars="Name",
    var_name="Subject",
    value_name="Score"
)

df_long

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [10]:
print(df.columns.tolist())

['Name', 'Math', 'Science', 'English']

In [9]:
df.pivot(index="Name", columns="Subject", values="Score")

KeyError: 'Subject'