Merging & Joining Data
Often, data is split across multiple tables or files. Pandas lets you combine them just like SQL — or even more flexibly!

In [1]:
import pandas as pd

In [4]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

Inner Join (default)

In [5]:
pd.merge(employees,departments, on="DeptID") # inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

Keeps all employees, fills NaN where no match.

In [10]:
pd.merge(employees,departments, on="DeptID",how="left") # left join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

Keeps all departments, even if no employee.

In [11]:
pd.merge(employees,departments, on="DeptID",how="right") # right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [12]:
pd.merge(employees,departments, on="DeptID",how="outer") # outerjoin Includes all data, fills missing with NaN.

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [17]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"] , "score":[12,34]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"],"age": [23,44]})

      Name  score   age
0    Alice   12.0   NaN
1      Bob   34.0   NaN
0  Charlie    NaN  23.0
1    David    NaN  44.0

In [19]:
df1

    Name  score
0  Alice     12
1    Bob     34

In [20]:
df2

      Name  age
0  Charlie   23
1    David   44

In [21]:
pd.concat([df1, df2])

      Name  score   age
0    Alice   12.0   NaN
1      Bob   34.0   NaN
0  Charlie    NaN  23.0
1    David    NaN  44.0

In [22]:
pd.concat([df1, df2], axis=1)

    Name  score     Name  age
0  Alice     12  Charlie   23
1    Bob     34    David   44

In [23]:
pd.concat([df1, df2], axis=0)

      Name  score   age
0    Alice   12.0   NaN
1      Bob   34.0   NaN
0  Charlie    NaN  23.0
1    David    NaN  44.0